language: java
#before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y rpm
  - mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true --settings settings.xml -B -V
#script: ./travis-script.sh
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn site --settings settings.xml -B -V
branches:
  except:
    - gh-pages
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/47b10b81867bd0063cf5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
